version: "3"

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.client.dev
    environment:
      - REACT_APP_PORT=3000
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 3000:3000
    volumes:
      - ./client/src:/app/client/src
      - ./client/public:/app/client/public
    links:
      - server
    command: npm run start
    restart: always
    stdin_open: true
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.server.dev
    expose:
      - 4000
    environment:
      - MONGO_URI=mongodb://db:27017/db
      - PORT=4000
      - NODE_ENV=development
    volumes:
      - ./server/src:/app/server/src
    links:
      - db
    restart: always
  db:
    image: mongo
    expose:
        - 27017
    restart: always